### ISSUE TITLE
Failed to verify username!

### ISSUE THREAD

**Issue by leopoldhub** [7ixi0/node-minecraft-proxy#6]
Hi, I lauched your proxy example and got the following error on my hub server:

`lost connection: Failed to verify username!`

as for the proxy:

`Connection lost, timed out`

Did I do something wrong? thx

**Comment by leopoldhub** [comment]
By the way my all my servers are online mode

**Comment by leopoldhub** [comment]
Ok, it was that... hub server cant be online mode... 
Is there a way to redirect to an online mode server anyway? thx

**Comment by leopoldhub** [comment]
Ok, I found the solution, it will need a bit of work but is doable.

**Comment by BasToTheMax** [comment]
> Ok, I found the solution, it will need a bit of work but is doable.

What is your solution?

**Comment by leopoldhub** [comment]
> > Ok, I found the solution, it will need a bit of work but is doable.
> 
> What is your solution? 

Its been 5 months, sorry but I dont remember... -_-

**Comment by BasToTheMax** [comment]
Oke

**Comment by BasToTheMax** [comment]
No problem
